code --install-extension Angular.ng-template
code --install-extension bierner.color-info
code --install-extension christian-kohler.npm-intellisense
code --install-extension Compulim.vscode-clock
code --install-extension cyrilletuzi.angular-schematics
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension HookyQR.beautify
code --install-extension johnpapa.Angular2
code --install-extension karigari.chat
code --install-extension leizongmin.node-module-intellisense
code --install-extension mohsen1.prettify-json
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension shakram02.bash-beautify
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Zignd.html-css-class-completion
